# Generated by Django 4.2.13 on 2024-06-15 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0002_alter_customer_email_alter_vehicle_vin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='mileage',
        ),
    ]
