# Generated by Django 4.2.13 on 2024-06-08 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services_app', '0001_initial'),
        ('customers_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('date', models.DateField(auto_created=True)),
                ('workOrder_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_description', models.CharField(max_length=1000)),
                ('notes', models.CharField(max_length=1000)),
                ('complete', models.BooleanField(default=False)),
                ('customer_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customers_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrderDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('part_quality', models.IntegerField()),
                ('service_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='services_app.services')),
                ('workOrder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workOrders_app.workorder')),
            ],
        ),
    ]
