# Generated by Django 4.2.13 on 2024-06-11 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0001_initial'),
        ('workOrders_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderdetail',
            name='part_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory_app.inventory'),
        ),
    ]
