# Generated by Django 4.2.13 on 2024-06-15 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrders_app', '0003_alter_workorderdetail_service_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='vehicle_mileage',
            field=models.IntegerField(default=0),
        ),
    ]
